/* ============================================================================
 * combus_ids_remote_md5.h  —  AUTO-GENERATED by scripts/combus_md5.py
 *
 * DO NOT EDIT. Re-generated on every PlatformIO build. Gitignored.
 *
 * MD5 computed from:
 *   - PROJECT_VERSION_MAJOR / MINOR
 *   - combus_ids_remote_analog.inc
 *   - combus_ids_remote_digital.inc
 *   - all recursively resolved #include contents
 *   - evaluated #ifdef blocks against build flags: ['BOARD_DC_DRIVER_DRV8801', 'BOARD_ESP32_8M_6S', 'COMBUS_UART_TX', 'DEBUG_DASHBOARD', 'DEBUG_HW', 'DEBUG_MONITOR_BAUD', 'DEBUG_SYSTEM', 'HAS_FAILSAFE', 'INPUT_PS4_DS4_BT', 'IS_MACHINE', 'IS_MAINBOARD', 'MACHINE_VOLVO_A60_H_BRUDER', 'MOTION_ENABLED', 'PAUSE_LOG_AFTER_INIT', 'PS4_BLUETOOTH_ADDRESS', 'VBAT_LIPO']
 *
 * Configuration folder: src/core/config/machines/dumper_truck/combus
 * ============================================================================
 */

#pragma once

#include <stdint.h>

namespace combus {
namespace wire {

static constexpr uint8_t kCombusWireMd5[16] = {
    0x76u, 0x08u, 0x0Cu, 0x71u, 0x14u, 0xCEu, 0x27u, 0x04u, 0x19u, 0x95u, 0x66u, 0xACu, 0x74u, 0xDCu, 0x42u, 0x24u
};

static constexpr uint8_t kProjectVersionMajor = 0u;
static constexpr uint8_t kProjectVersionMinor = 1u;

static constexpr uint8_t kCombusHandshakeWirePayloadLen = 18u;

} // namespace wire
} // namespace combus
