/*!****************************************************************************
 * @file  combus_types.h
 * @brief ComBus type dispatch — selects the machine-family channel ID enums
 *         (AnalogComBusID / DigitalComBusID) and re-exports them at the
 *         call site for transparent access from core modules.
 *
 * USAGE
 *   #include <core/config/machines/combus_types.h>
 *   combus_set_digital(comBus, DigitalComBusID::FAILSAFE_VBAT, true);
 *
 *   This is the single entry point for core code (vbat, light, sound_module,
 *   dashboard helpers, ...) that needs to reference machine-specific channel
 *   IDs without dragging in the machine configuration explicitly.
 *
 *   The generated `combus_ids.h` is produced by the combus_builder v2 hook
 *   (scripts/combus_scons_hook.py) and placed under
 *   <PROJECT_BUILD_DIR>/combus_generated/. The hook also adds that directory
 *   to the include path, so a bare `#include <combus_ids.h>` is enough.
 *
 *   IMPORTANT: this dispatcher is kept intentionally thin. The generator
 *   emits the enums in the global scope (no per-machine namespace) — see
 *   scripts/combus_builder/generator.py. If/when a multi-machine remote
 *   build requires per-machine namespacing, reintroduce it here AND in the
 *   generator template.
 *******************************************************************************///
#pragma once

#include <core/system/combus/combus_defs.h>  // ChanLayer / Direction / ComBus (runtime struct)

// The combus_scons_hook.py adds <build_dir>/combus_generated to CPPPATH and
// emits combus_ids.h there. Including it gives the full enum definitions.
#include <combus_ids.h>  // generated by scripts/combus_builder (A6.1)

// EOF combus_types.h
