#!/usr/bin/env python3
"""
combus_builder/md5.py - A7.1: MD5 computation for the combus_remote view.

Generates a deterministic 16-byte MD5 hash of the combus_remote view's
channel definitions (id, type, scope, theme, direction, infoName).
The hash is independent of:
  - file discovery order
  - YAML formatting, comments
  - key ordering within channel dicts
  - `requires` (its effect is already captured by the channel's
    presence/absence in the view after A6.1 resolution)

The hash does NOT cover projectVersion — that is exposed as a separate
constant so the handshake can produce a precise diagnostic on mismatch
(option B in the A7 prompt).

A7.1 simplifications vs A7:
  - Single MD5 (combus_remote only). combus_local was speculative for
    inter-node alignment and is not consumed by the handshake consumer
    (combus_handshake.h references a single kCombusWireMd5[16]).
  - REMOVED kMachineType. The MD5 REMOTE is already the source of truth
    for cross-machine-type compatibility. Legacy scripts/combus_md5.py
    on combus-frame-handshake did not emit it either.
  - REMOVED _detect_machine_type() and the AMBIGUOUS guard. No longer
    needed since kMachineType is gone.

Canonical representation:
  - JSON with sort_keys=True over a fixed list of fields per channel.
  - Channels ordered by (scope priority, type, theme, id) — the same
    canonical order used by _select_view() in generator.py.
  - Field per channel: id, type, scope, theme, direction (sorted list),
    infoName.

C++ emission policy:
  - `static constexpr` (linkage-safe pattern that works on every
    supported toolchain, including xtensa-esp32-elf-g++).
  - Single file: combus_remote_md5.h.
  - Constants emitted:
      kCombusRemoteComBusMd5[16]            raw MD5 bytes (wire)
      kCombusRemoteComBusMd5Hex             32-char lowercase hex (log)
      kProjectVersionMajor / Minor          placeholder 0/1
      kCombusHandshakeWirePayloadLen        18 (= 16 md5 + 2 version)
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from .generator import View, ViewChannel


# =============================================================================
# CANONICAL SERIALIZATION
# =============================================================================

def _view_channel_canonical(vc: ViewChannel) -> dict:
    """Return a JSON-serialisable dict representing one channel.

    The dict keys are a fixed list (no per-channel metadata). The direction
    is sorted to remove any ordering ambiguity. `infoName` is included so
    that renaming a debug label changes the hash.
    """
    direction = sorted(vc.ch.direction)
    return {
        "id": vc.ch.id,
        "type": vc.ch.type,
        "scope": vc.ch.scope,
        "theme": vc.ch.theme,
        "direction": direction,
        "infoName": vc.ch.info_name,
    }


def canonical_bytes(view: View) -> bytes:
    """Return the canonical byte representation of a view, suitable for hashing."""
    payload = {
        "view": view.name,
        "channels": [_view_channel_canonical(vc) for vc in view.channels],
    }
    return json.dumps(
        payload,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")


# =============================================================================
# HASH COMPUTATION
# =============================================================================

@dataclass(frozen=True)
class ViewHash:
    """The result of hashing a view.

    view_name: which view was hashed (combus_remote).
    md5_hex:   32-char lowercase hex string (128 bits).
    digest:    raw 16-byte MD5 digest.
    """
    view_name: str
    md5_hex: str
    digest: bytes


def compute_view_hash(view: View) -> ViewHash:
    """Compute MD5(canonical channels JSON) for the given view."""
    payload = canonical_bytes(view)
    digest = hashlib.md5(payload).digest()
    return ViewHash(
        view_name=view.name,
        md5_hex=digest.hex(),
        digest=digest,
    )


# =============================================================================
# C++ RENDERING
# =============================================================================

_CPP_HEADER_PROLOGUE = """\
/******************************************************************************
 * GENERATED FILE - DO NOT EDIT.
 *
 * Generated by scripts/combus_builder/generator.py (A7.1).
 * View: combus_remote
 * Hash inputs: id, type, scope, theme, direction, infoName
 *              (independent of file order, YAML formatting, requires).
 * ProjectVersion: <project_version>
 *
 * MD5 does NOT include projectVersion — emitted as a separate constant
 * below (option B: separate hash + version for precise mismatch
 * diagnostics). See doc/combus_v2 - YAML implementation.md §13.
 *
 * Regenerate on every PlatformIO build via the combus_builder extra_script.
 * Do not commit this file to the source tree.
 ******************************************************************************/
"""

_PROJECT_VERSION_MAJOR_PLACEHOLDER = 0
_PROJECT_VERSION_MINOR_PLACEHOLDER = 1


def _render_md5_header(
    hash_: ViewHash,
    project_version_major: int = _PROJECT_VERSION_MAJOR_PLACEHOLDER,
    project_version_minor: int = _PROJECT_VERSION_MINOR_PLACEHOLDER,
) -> str:
    """Render the combus_remote_md5.h file.

    Emitted constants:
      - kCombusRemoteComBusMd5[16]            raw MD5 bytes (wire)
      - kCombusRemoteComBusMd5Hex             32-char lowercase hex (log)
      - kProjectVersionMajor / Minor          placeholder 0/1
      - kCombusHandshakeWirePayloadLen        18 (= 16 md5 + 2 version)
    """
    digest = hash_.digest
    hex_str = hash_.md5_hex

    body: list[str] = []
    body.append(_CPP_HEADER_PROLOGUE
                .replace("<project_version>",
                         f"{project_version_major}.{project_version_minor}"))
    body.append("")
    body.append("#pragma once")
    body.append("")
    body.append("#include <stdint.h>")
    body.append("")
    body.append("namespace combus {")
    body.append("namespace wire {")
    body.append("")
    body.append("/// MD5 hash of the canonical channel set for the combus_remote view.")
    body.append("/// 16 raw bytes (suitable for wire embedding).")
    body.append("static constexpr uint8_t kCombusRemoteComBusMd5[16] = {")
    body.append("    " + ", ".join(f"0x{b:02X}u" for b in digest))
    body.append("};")
    body.append("")
    body.append("/// Same MD5 as a 32-char lowercase hex string (debug/log).")
    body.append("static constexpr const char* kCombusRemoteComBusMd5Hex =")
    body.append(f'    "{hex_str}";')
    body.append("")
    body.append("/// Project version (placeholder 0.1 until project_version.h is introduced).")
    body.append(f"static constexpr uint8_t kProjectVersionMajor = {project_version_major}u;")
    body.append(f"static constexpr uint8_t kProjectVersionMinor = {project_version_minor}u;")
    body.append("")
    body.append("/// Total handshake wire payload length = 16 (md5) + 2 (version).")
    body.append("static constexpr uint8_t kCombusHandshakeWirePayloadLen = 18u;")
    body.append("")
    body.append("} // namespace wire")
    body.append("} // namespace combus")
    body.append("")
    body.append("// EOF")
    return "\n".join(body) + "\n"


def emit_md5_header(
    hash_: ViewHash,
    out_dir,
    project_version_major: int = _PROJECT_VERSION_MAJOR_PLACEHOLDER,
    project_version_minor: int = _PROJECT_VERSION_MINOR_PLACEHOLDER,
) -> "Path":
    """Render and write the combus_remote_md5.h file into out_dir."""
    from pathlib import Path
    from .generator import _safe_write

    content = _render_md5_header(
        hash_,
        project_version_major=project_version_major,
        project_version_minor=project_version_minor,
    )
    out_path = Path(out_dir) / "combus_remote_md5.h"
    _safe_write(out_path, content)
    return out_path


# =============================================================================
# PUBLIC ENTRY POINT
# =============================================================================

def generate_md5_artifacts(
    sel,
    out_dir,
    project_version_major: int = _PROJECT_VERSION_MAJOR_PLACEHOLDER,
    project_version_minor: int = _PROJECT_VERSION_MINOR_PLACEHOLDER,
):
    """Compute MD5 for combus_remote and write combus_remote_md5.h into out_dir.

    A7.1: only combus_remote is hashed. combus (full) and combus_local
    are intentionally NOT hashed — the handshake consumer references a
    single kCombusWireMd5[16] (combus_handshake.h).

    Returns: (hash_, written_path)
    """
    hash_ = compute_view_hash(sel.remote)
    written = emit_md5_header(
        hash_,
        out_dir,
        project_version_major=project_version_major,
        project_version_minor=project_version_minor,
    )
    return hash_, written
