/*!****************************************************************************
 * @file  combus_ids_remote.h
 * @brief Dumper-truck REMOTE-only channel IDs — generic vocabulary for ALL dumper-truck instances
 *
 * SHIM: this file used to assemble enums from local .inc fragments.
 * After the combus_builder v2 migration (2026-08-22), all channels are
 * declared in input.cb / *.cb and assembled by the generator hook.
 *
 * This shim simply forwards to the generated combus_remote_ids.h, which
 * declares `AnalogComBusRemoteID` (REMOTE view). Note: `DigitalComBusRemoteID`
 * is intentionally NOT generated here — digital REMOTE channels are not
 * transmitted as packed bits in the current wire protocol. Code that needs
 * a REMOTE digital vocabulary should be updated to use a different mechanism.
 *
 * Do NOT add anything here — the legacy .inc fragments are deprecated.
 *******************************************************************************///
#pragma once

#include <combus_remote_ids.h>  // generated by scripts/combus_builder (A6.1)
