/*!****************************************************************************
 * @file  combus_ids.h
 * @brief ComBus channel ID enumerations — Volvo A60H Bruder (type: dumper_truck)
 *
 * SHIM: this file used to assemble enums from local .inc fragments.
 * After the combus_builder v2 migration (2026-08-22), all channels are
 * declared in input.cb / *.cb and assembled by the generator hook.
 *
 * This shim simply forwards to the generated combus_ids.h.
 *
 * Do NOT add anything here — the legacy .inc fragments are deprecated.
 *******************************************************************************///
#pragma once

#include "combus_ids.h"  // generated by scripts/combus_builder (A6.1)
