/*!****************************************************************************
 * @file  combus.h
 * @brief ComBus — Volvo A60H Bruder — externs runtime
 *
 * SHIM: this file used to declare the externs (AnalogComBusArray,
 * DigitalComBusArray, comBus) and include the .inc fragments.
 *
 * After the combus_builder v2 migration (2026-08-22), everything is
 * declared and assembled by the generator hook. This shim just
 * forwards to the generated combus.h.
 *
 * Do NOT add anything here — the legacy .inc fragments are deprecated.
 *******************************************************************************///
#pragma once

#include "combus.h"  // generated by scripts/combus_builder (A6.1)
