/*!****************************************************************************
 * @file  combus.h
 * @brief ComBus — Volvo A60H Bruder — externs runtime
 *
 * SHIM: this file used to declare the externs (AnalogComBusArray,
 * DigitalComBusArray, comBus) and include the .inc fragments.
 *
 * After the combus_builder v2 migration (2026-08-22), everything is
 * declared and assembled by the generator hook. This shim forwards
 * to the generated combus.h (which lives under <PROJECT_BUILD_DIR>/
 * combus_generated/ and is on CPPPATH via env.Append + projenv.Append
 * in scripts/combus_scons_hook.py).
 *
 * We use chevrons (`<combus.h>`) rather than quotes (`"combus.h"`)
 * because the shim's own filename is combus.h. With quotes, the
 * preprocessor would resolve the include to the shim itself, hit
 * `#pragma once`, and the real generated combus.h would never be
 * included — leaving the consumers with an empty `AnalogComBusID`
 * enum and the "X is not a member" compile errors observed in
 * A12 investigation.
 *
 * Do NOT add anything here — the legacy .inc fragments are deprecated.
 *******************************************************************************///
#pragma once

#include <combus.h>  // generated by scripts/combus_builder (A6.1)
